# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_vehicle_name', models.CharField(max_length=256)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_path', to='schoolyears.Path')),
                ('next_route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolyears.RouteInfo')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='schoolyears.Node')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_colors', models.CharField(choices=[('GR', '97FFAD'), ('RE', 'F08F90'), ('BL', '3FC0FF'), ('YE', 'F5D76E'), ('OR', 'FABE58'), ('PU', 'AEA8D3')], default='GR', max_length=2)),
                ('school_type', models.CharField(choices=[('ES', 'Elementary School'), ('JS', 'Junior High School'), ('HS', 'High School')], default='ES', max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('name_kanji', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=16)),
                ('website', models.CharField(max_length=256)),
                ('principal', models.CharField(max_length=128)),
                ('vice_principal', models.CharField(max_length=128)),
                ('english_head_teacher', models.CharField(max_length=128)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=128)),
                ('source_name', models.CharField(max_length=128)),
                ('destination_name', models.CharField(max_length=128)),
                ('is_round_trip', models.BooleanField(default=True)),
                ('total_cost', models.IntegerField(default=0)),
                ('is_alt_meeting', models.BooleanField(default=False)),
                ('calculated_total_cost', models.IntegerField(default=0)),
                ('travel_method', models.CharField(choices=[('01.Not Selected', 'Not Selected'), ('02.Train', 'Train'), ('03.Bus', 'Bus'), ('04.Train/Bus', 'Train/Bus')], default='01.Not Selected', max_length=16)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolyears.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialYearlySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_event', models.CharField(choices=[('TBA', 'TBA'), ('MTG', 'ALT Meeting'), ('WKD', 'Work day')], default='TBA', max_length=3)),
                ('special_colors', models.CharField(choices=[('TBA', 'D4AF37'), ('MTG', 'BCAAA4'), ('WKD', 'CC9259')], default='TBA', max_length=3)),
                ('date', models.DateField()),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.SchoolYear')),
            ],
        ),
        migrations.CreateModel(
            name='YearlySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.School')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.SchoolYear')),
            ],
        ),
        migrations.AddField(
            model_name='schoolroute',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.SchoolYear'),
        ),
        migrations.AddField(
            model_name='schoolroute',
            name='source_route_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolyears.RouteInfo'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.SchoolYear'),
        ),
    ]
