# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolyears', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolroute',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
