# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolyears', '0002_schoolroute_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_colors',
            field=models.CharField(choices=[('GR', '97FFAD'), ('RE', 'F08F90'), ('BL', '3FC0FF'), ('YE', 'F5D76E'), ('OR', 'FABE58'), ('PU', 'AEA8D3')], default='GR', max_length=32),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('ES', 'Elementary School'), ('JS', 'Junior High School'), ('HS', 'High School')], default='ES', max_length=32),
        ),
        migrations.AlterField(
            model_name='specialyearlyschedule',
            name='special_colors',
            field=models.CharField(choices=[('TBA', 'D4AF37'), ('MTG', 'BCAAA4'), ('WKD', 'CC9259')], default='TBA', max_length=32),
        ),
        migrations.AlterField(
            model_name='specialyearlyschedule',
            name='special_event',
            field=models.CharField(choices=[('TBA', 'TBA'), ('MTG', 'ALT Meeting'), ('WKD', 'Work day')], default='TBA', max_length=32),
        ),
    ]
