# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolyears', '0003_auto_20180911_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolroute',
            name='index',
        ),
    ]
