# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(default=1234567)),
                ('alt_name', models.CharField(default='John Smith', max_length=64)),
                ('board_of_education', models.CharField(default='Sagamihara-shi', max_length=64)),
                ('sales_person', models.CharField(default='Yamada Taku', max_length=64)),
                ('fax', models.CharField(default='045-242-7779', max_length=64)),
                ('telephone', models.CharField(default='045-242-7555', max_length=12)),
                ('interac_email', models.CharField(default='user@interacmail.com', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
