# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 03:58
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('schoolyears', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.SmallIntegerField()),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPeriodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=64)),
                ('period_type', models.CharField(choices=[('NORM', 'Normal days (Tue/Thu/Fri)'), ('MOND', 'Mondays'), ('WEDN', 'Wednesdays'), ('SPEC', 'Special days'), ('SATU', 'Saturdays')], default='NORM', max_length=2)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.SmallIntegerField(default=1)),
                ('section_count', models.SmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSectionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Course')),
                ('school_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolSection')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=5)),
                ('teacher_name', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('student_count', models.SmallIntegerField(default=30)),
                ('school_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolSection')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson_number', models.SmallIntegerField()),
                ('hour_number', models.SmallIntegerField()),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.LessonPlan')),
                ('school_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolPeriod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPeriodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyears.School')),
                ('school_period_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolPeriodType')),
            ],
        ),
        migrations.AddField(
            model_name='schoolperiod',
            name='school_period_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolPeriodType'),
        ),
    ]
