# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolperiodtype',
            name='period_type',
            field=models.CharField(choices=[('NORM', 'Normal days (Tue/Thu/Fri)'), ('MOND', 'Mondays'), ('WEDN', 'Wednesdays'), ('SPEC', 'Special days'), ('SATU', 'Saturdays')], default='NORM', max_length=32),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=16),
        ),
    ]
