# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20190107_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolperiodtype',
            name='period_type',
            field=models.CharField(choices=[('NORM', 'Normal days'), ('MOND', 'Mondays'), ('WEDN', 'Wednesdays'), ('SPEC', 'Special days'), ('SATU', 'Saturdays')], default='NORM', max_length=32),
        ),
    ]
