# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20190327_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionperiod',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
