# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_sectionperiod_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePeriodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField()),
                ('school_period_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolPeriodType')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSectionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SchoolPeriod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Section')),
            ],
        ),
    ]
