# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolyears', '0005_auto_20190327_2316'),
        ('schedules', '0007_templateperiodtype_templatesectionperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateperiodtype',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoolyears.School'),
        ),
    ]
