# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-07 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_templateperiodtype_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesectionperiod',
            name='weekday',
            field=models.SmallIntegerField(default=0),
        ),
    ]
