# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lessons.filefield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_source_type', models.CharField(choices=[('BF', "Book-Free Activities -- These don't require the book."), ('BB', 'Book-Bound Activities -- These require the book.')], default='BF', max_length=2)),
                ('activity_skill_type', models.CharField(choices=[('VO', 'Vocabulary Practice'), ('CO', 'Conversation Practice'), ('LI', 'Listening Practice'), ('OT', 'Other Skills (e.g.: song, dance)')], default='VO', max_length=2)),
                ('activity_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('materials', models.CharField(default=None, max_length=256)),
                ('activity_portion_type', models.CharField(choices=[('GE', 'Generic/Other'), ('GR', 'Greeting'), ('WA', 'Warmup'), ('PE', 'Presentation'), ('PA', 'Practice'), ('PO', 'Production'), ('CO', 'Cooldown'), ('AS', 'Assessment')], default=None, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_file', lessons.filefield.ContentTypeRestrictedFileField(upload_to='static/files/')),
                ('original_filename', models.CharField(max_length=128)),
                ('notes', models.TextField()),
                ('is_link_to_existing_file', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('course_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('PO', 'Portrait'), ('LA', 'Landscape')], default='PO', max_length=2)),
                ('flashcard_type', models.CharField(choices=[('PL', 'Flashcard with picture and label'), ('PO', 'Flashcard with picture only'), ('FB', 'Two pages: front (picture) and back (label)')], default='PL', max_length=2)),
                ('picture', lessons.filefield.ContentTypeRestrictedFileField(upload_to='static/files/flashcards/')),
                ('label', models.CharField(max_length=128)),
                ('notes', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Flashcard')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Course')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_number', models.SmallIntegerField(null=True)),
                ('is_premade_lesson_plan', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='lessons.Activity')),
                ('cooldown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooldown', to='lessons.Activity')),
                ('greeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greeting', to='lessons.Activity')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
                ('practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='lessons.Activity')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='lessons.Activity')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='lessons.Activity')),
                ('warmup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warmup', to='lessons.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='flashcardlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
    ]
