# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_skill_type',
            field=models.CharField(choices=[('VO', 'Vocabulary Practice'), ('CO', 'Speaking Practice'), ('LI', 'Listening Practice'), ('OT', 'Other Skills (e.g.: song, dance)')], default='VO', max_length=2),
        ),
    ]
