# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180425_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardlesson',
            name='is_link_to_existing_flashcard',
            field=models.BooleanField(default=False),
        ),
    ]
