# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_flashcardlesson_is_link_to_existing_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_bordered',
            field=models.BooleanField(default=True),
        ),
    ]
