# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-06 04:19
from __future__ import unicode_literals

from django.db import migrations
import lessons.filefield


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20180911_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='picture',
            field=lessons.filefield.ContentTypeRestrictedFileField(upload_to='static/media/flashcards/'),
        ),
    ]
