# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-12 04:26
from __future__ import unicode_literals

from django.db import migrations
import lessons.filefield


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20190131_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='picture',
            field=lessons.filefield.ContentTypeRestrictedFileField(upload_to='media/flashcards/'),
        ),
    ]
