# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20190328_1351'),
        ('lessons', '0008_auto_20190212_1326'),
    ]

    operations = [
    ]
